Code optimization

diff --git a/script/pre-commit b/script/pre-commit
--- a/script/pre-commit
+++ b/script/pre-commit
@@ -1,36 +1,68 @@
-#!/usr/bin/env ruby
+#!/bin/sh
 
-# frozen_string_literal: true
+red='\033[0;31m'
+green='\033[0;32m'
+yellow='\033[0;33m'
+NC='\033[0m'
 
-### Updating version
+if git rev-parse --verify HEAD >/dev/null 2>&1; then
+  against=HEAD
+else
+  # Initial commit: diff against an empty tree object
+  # Change it to match your initial commit sha
+  against=123acdac4c698f24f2352cf34c3b12e246b48af1
+fi
 
-new_version = Time.now.strftime('%Y%m%d.%H%M%S.%L')
+# Check if rubocop is installed for the current project
+rubocop -v >/dev/null 2>&1 || { echo >&2 "${red}[Ruby Style][Fatal]: Add rubocop to your Gemfile"; exit 1; }
 
-version_file = 'lib/data_modeller/version.rb'
-if File.exist?(version_file)
-  text = File.read(version_file)
-  File.open(version_file, 'w') { |file| file << text.sub(/VERSION = '.+'/, "VERSION = '#{new_version}'") }
-  system("git add #{version_file}")
-end
+# Get only the staged files
+FILES="$(git diff --cached --name-only --diff-filter=AMC | grep "\.rb$" | tr '\n' ' ')"
 
-gemfile = 'Gemfile.lock'
-if File.exist?(gemfile)
-  text = File.read(gemfile)
-  File.open(gemfile, 'w') { |file| file << text.sub(/rails-data-modeller \([^)]+\)/, "rails-data-modeller (#{new_version})") }
-  system("git add #{gemfile}")
-end
+# echo "${green}[Ruby Style][Info]: Checking Ruby Style${NC}"
 
-### Verifying changes with rubocop
+if [ -n "$FILES" ]; then
+  # echo "${green}[Ruby Style][Info]: ${FILES}${NC}"
 
-require 'rubocop'
+  if [ ! -f '.rubocop.yml' ]; then
+    echo "${yellow}[Ruby Style][Warning]: No .rubocop.yml config file.${NC}"
+  fi
 
-ADDED_OR_MODIFIED = /A|AM|^M/
+  # Run rubocop on the staged files
+  rubocop --force-exclusion ${FILES}
 
-changes = `git status --porcelain`.split(/\n/)
-changes.select! { |file_name_with_status| file_name_with_status =~ ADDED_OR_MODIFIED }
-changed_files = changes.map { |file_name_with_status| file_name_with_status.split[1] }
+  if [ $? -ne 0 ]; then
+    echo "${red}[Ruby Style][Error]: Fix the issues and commit again${NC}"
+    exit 1
+  fi
+else
+  echo "${green}[Ruby Style][Info]: No files to check${NC}"
+fi
 
-ruby_files = changed_files.select { |file_name| File.extname(file_name) == '.rb' }
-system("rubocop --force-exclusion #{ruby_files.join(' ')}") unless ruby_files.empty?
+# Check if slim-lint is installed for the current project
+slim-lint -v >/dev/null 2>&1 || { exit 0; }
 
-exit $CHILD_STATUS.to_s[-1].to_i
+# Get only the staged files
+FILES="$(git diff --cached --name-only --diff-filter=AMC | grep "\.slim$" | tr '\n' ' ')"
+
+# echo "${green}[Slim Style][Info]: Checking Slim Style${NC}"
+
+if [ -n "$FILES" ]; then
+  # echo "${green}[Slim Style][Info]: ${FILES}${NC}"
+
+  if [ ! -f '.slim-lint.yml' ]; then
+    echo "${yellow}[Slim Style][Warning]: No .slim-lint.yml config file.${NC}"
+  fi
+
+  # Run slim-lint on the staged files
+  slim-lint ${FILES}
+
+  if [ $? -ne 0 ]; then
+    echo "${red}[Slim Style][Error]: Fix the issues and commit again${NC}"
+    exit 1
+  fi
+else
+  echo "${green}[Slim Style][Info]: No files to check${NC}"
+fi
+
+exit 0
